[package]
name = "client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-std = "1.12.0"
chrono = "0.4.35"
druid = "0.8.3"
futures = "0.3.30"

[profile.release]
lto = true
opt-level = "z"
